ifneq ($(CONFIG_PREBUILT_APK), true)
ifeq ($(CONFIG_REMOTE_ONLINE_SUPPORTED), true)
ifeq ($(TARGET_CPU_ABI), arm64-v8a)

LOCAL_PATH := $(call my-dir)

ifneq ($(shell expr $(PLATFORM_SDK_VERSION) \>= 26),0)
LOCAL_USE_PROPRIETARY_MODULE := false
else
LOCAL_USE_PROPRIETARY_MODULE := true
endif

include $(CLEAR_VARS)
LOCAL_MODULE := libijkffmpeg
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_PROPRIETARY_MODULE := $(LOCAL_USE_PROPRIETARY_MODULE)
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := ./libs/arm64-v8a/libijkffmpeg.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libijkplayer
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_PROPRIETARY_MODULE := $(LOCAL_USE_PROPRIETARY_MODULE)
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := ./libs/arm64-v8a/libijkplayer.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libijksdl
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_PROPRIETARY_MODULE := $(LOCAL_USE_PROPRIETARY_MODULE)
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := ./libs/arm64-v8a/libijksdl.so
include $(BUILD_PREBUILT)

endif
endif
endif